image: podkovyrovda/mytracky:test

stages:
  - build

variables:
  DATABASE_USERNAME: "$DATABASE_USERNAME"
  DATABASE_PASSWORD: "$DATABASE_PASSWORD"
  TEST_DATABASE_NAME: "$TEST_DATABASE_NAME"

before_script:
  - eval $(ssh-agent -s) && ssh-add <(echo "$PRIVATE_SSH")
  - /etc/init.d/mysql start
  - mysqladmin -u "$DATABASE_USERNAME" -p123 password "$DATABASE_PASSWORD"
  - mysqladmin -u "$DATABASE_USERNAME" -p"$DATABASE_PASSWORD" create "$TEST_DATABASE_NAME"

build:
  stage: build  
  script:
    - mvn package -Dmaven.test.skip=true
    - scp target/*.jar root@gitlab.podkovyrov.ru:/root/docker/server/src/app.jar
    - ssh root@gitlab.podkovyrov.ru 'cd docker && docker-compose up -d --no-deps --build server'
